version: 2
jobs:
  build:
    docker:
      - image: athos/clj-lib-dev

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run: clojure -A:check:test -Stree

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run:
          name: check
          command: clojure -Acheck

      - run:
          name: test
          command: clojure -Atest
